"""MCP server for the Mental Health KG, generated by `samyama_mcp`.

Tools come from two places. Most are generated from the live schema — count,
find_connections and traverse per label and edge type, plus schema_info,
cypher_query and the graph algorithms. The rest are declared in `config.yaml`
as the questions this graph exists to answer: referral lookup, exclusion,
language, coverage, licensed capacity and federal shortage designations.

    # against a running server holding the four-source graph
    python -m mcp_server.server --url http://localhost:18080

    # what is exposed, without starting anything
    python -m mcp_server.server --list-tools

Claude Desktop:

    {"mcpServers": {"mental-health-kg": {
        "command": "python",
        "args": ["-m", "mcp_server.server", "--url", "http://localhost:18080"]}}}

**A server is required; embedded mode is deliberately not offered.** PyPI
`samyama` 0.6.1 inverts `OPTIONAL MATCH … IS NULL` when the engine runs
in-process, so `find_referral_excluding` would return exactly the facilities it
is meant to rule out — the wrong answer, with no error, to the one question
where being wrong matters most. Against a server the same query is correct
(verified: 127 facilities in MA, not 11). See `docs/schema.md`.

Building the graph is `etl/`, not this module: the layers arrive from four
sources and the NPPES pass alone streams 11.6 GB. Import a snapshot instead —
`demo/README.md` has the two commands.
"""

from __future__ import annotations

import argparse
import os
import sys

DEFAULT_URL = "http://localhost:18080"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="mental-health-kg-mcp",
        description="Mental Health KG MCP server (powered by samyama_mcp)",
    )
    parser.add_argument(
        "--url",
        default=os.environ.get("MH_URL", DEFAULT_URL),
        help=f"Samyama server to query (default: $MH_URL or {DEFAULT_URL}).",
    )
    parser.add_argument(
        "--graph",
        default="mental-health",
        help="Graph/tenant to serve (default: %(default)s).",
    )
    parser.add_argument(
        "--name",
        default="Mental Health KG",
        help="MCP server name.",
    )
    parser.add_argument(
        "--list-tools",
        action="store_true",
        help="Print the tools this would expose and exit.",
    )
    args = parser.parse_args(argv)

    server = build_server(args.url, graph=args.graph, name=args.name)

    if args.list_tools:
        tools = server.list_tools()
        print(f"{args.name}: {len(tools)} tools\n")
        for name in sorted(tools):
            print(f"  - {name}")
        return

    server.run()


def build_server(url: str, graph: str = "mental-health",
                 name: str = "Mental Health KG"):
    """Connect to `url` and build the server from `config.yaml`.

    Separate from main() so a test can build the server and inspect its tools
    without parsing arguments or starting a transport.
    """
    from samyama import SamyamaClient
    from samyama_mcp.config import ToolConfig
    from samyama_mcp.server import SamyamaMCPServer

    client = SamyamaClient.connect(url)
    config = ToolConfig.from_yaml(
        os.path.join(os.path.dirname(__file__), "config.yaml"))
    return SamyamaMCPServer(client, graph=graph, server_name=name, config=config)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
